apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: service-a
    app: service-a
  name: service-a
spec:
  source:
    git:
      ref: master
      uri: https://github.com/cesarvr/Spring-Boot 
    sourceSecret:
      name: gitsecret
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      env:
      - name: APPLICATION_NAME
        value: service-a 
      - name: PROJECT
        value: ctest
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
